### ISSUE TITLE
Rename ignore_older to close_older

### ISSUE THREAD

**Issue by ruflin** [elastic/filebeat#181]
`Ignore_older` sounds like files older then x are ignored from now on which is not correct. Every time it is scanned for new files, these files will be picked up again if they changed. The only thing it does is that it updates these files only with scan_frequency instead of continuous and closes the file handler. I suggest to rename this config to `close_older`.

**Comment by ruflin** [comment]
On the dicsussion with @tsg the following problems popped up:
* If a file is already "older" the ignore_older on startup, it will be ignored. So ignore_older is also somehow correct
* If a file is crawled but then not touched for more then ignore_older, the file handler will be closed

Both things are valuable but are somehow different options. Should we split it up?

**Comment by tbragin** [comment]
I'd recommend the name "ignore_inactive", since you are not closing simply older, but rather files that haven't been written to in a while.

**Comment by monicasarbu** [comment]
Yes, I agree we should definitely improve the naming, but I think this is something nice to have. I would postpone it for 1.1.x.

**Comment by tsg** [comment]
I'd be for separating the two settings, but am afraid of doing it for RC1, so +1 for postponing the change to 1.1. The change doesn't have to break compatibility, btw, we can keep the old option as deprecated and introduce two new settings.

**Comment by ruflin** [comment]
# Filebeat Configuration Options

Filebeat offers a wide variety of config options which affect how often files are read, files closed or new ones picked up. Below is a detailed explanation and definition of what the different configuration variables should do. This does not necessarily describe the current behavior, but the behavior it should have.


## ignore_older
Ignore_older is used to make sure old files are not picked up by the crawler. The following cases exist:

* On Startup
  * File was changed in the ignore_older period: Full file is read and sent
  * File was not change in the ignore_older period: File is not read, file pointer is set to the end of the file
  * File was not change in the ignore_older period but we have it in the registrar (read before): File pointer will be set to the end
* Running
  * New file added which is changed in ignore_older period: Full file is read and sent
  * New file added which is NOT changed in ignore_older: File is not read, file pointer is set to the end
  * File is updated: Only newly added lines are read
  * File was not change in the ignore_older period but we have it in the registrar (read before): File pointer will be set to the end


Edge cases
* scan_frequency is bigger then ignore_older: Every time the scan is run and an ignore_older file is found, the file pointer is set to the end. In this case it can happen that during scan_frequency a file was updated but not picked up yet, and when encountering scan_frequency it already falls under ignore_older, means the lines are never read.
* Updates happen less frequent then ignore_older: If an update to a file happens only every 2 hours and ignore_older is set to 30 minutes, it can happen that the new lines added are skipped, because when the file is found, it skips to the end first for reading. (This must be double checked)

### Recommended values
* ignore_older must be the largest values of the defined durations. It is recommended to set it to at least 24h or bigger. It must be larger then the least frequent updates of your files.

### Questions
* Should files which fall under ignore_older be added to the registrar? The potential problem here is that registrar can get really large.
* Should we offer the possibility to disable ignore_older, means setting it to infinit? 0 could be used for that.
* What are we doing with files we have in the registrar with offset that are updated and were falling under ignore_older before. Do we start at the last offset or from the end?



## close_older
Close older is used to close the file handler for files which were not updated in the period of close_older. Besides closing the file handler and not starting a new harvester before the file is read again, this has no implication at which stage the files are read.

The consequence of a file falling under close_older is that in the worst case a line is only picked up after scan_frequency instead of backoff. This removes the near real time feature for the files which are updated less frequent then close_older.

The goal of close_older is not to have too many open files to save resources.

### Recommended values
* close_older must be set smaller then ignore_older
* close_older should be larger then the most frequent update periods of files, but smaller then the least frequent updates
* If open files is not issue, this should be set to infinity

### Questions
* Should we offer to disable close_older, means setting it to infinity. We could use 0 for that.

## scan_frequency
scan_frequency is used on how often the file system is crawled for new files. Every time scan is run it checks for the following:
* New files to be harvested found?
* Existing files where the harvester was closed because of close_older but changed recently?

### Recommended values
* scan_frequency should be set to a value at least larger or equal to 10s. Having a very low scan_frequency can lead to race conditions.
* scan_frequency must be smaller then close_older
* scan_frequency must be smaller then ignore_older

## tail_files
Tail files is used to start reading new files at the end. The following cases exist:

* On Startup
  * All files are started reading on at the end
* Running
  * New file is discovered (for example file rotation): Reading starts at the end.

As reading starts always at the end, also for new files it can happen that some of the data is discarded, means log lines are lost.

### Recommended values
* tail_files is recommended to be set to false because of the potential log line loss.
* It is recommended to only use this value to set the state of the files ones and then restart filebeat without the option again.

### Questions
* Should we make it possible that tail_files only applies on the first scan of the file system and from then on it is not used anymore? What will happen if filebeat restarts?

## remove_older_state
remove_older_state is used to make sure the registrar file doesn't grow infinitely. This can happen in cases where random file names are generated to be picked up by filebeat. States which are ones added to the registrar will never be removed anymore. See also issue: https://github.com/elastic/filebeat/issues/269

Use cases:

* File is older then remove_older_state but still exists: State is not removed
* File is older then remove_older_state but is not on the file system anymore: State is removed

The state of old files should only be removed if they can't be found anymore during the next scan of the file system (scan_frequency). As long as a file exist on the file system, the state is kept.

Only files without an open harvester can be removed from the registrar, which means the files must either fall under ignore_older or close_older

### Recommended values
* By default it is not recommended to use this feature and set the value to 0, to have it set to infinity.
* If a value is set, it must be larger then scan_frequency and close_older.

### Questions
* Should we make the check if the file should be removed only on the file name (simple) or also the inode/device?

# Discussion
* Are the above assumptions correct?
* Do we have better names for the different config options?

**Comment by ruflin** [comment]
@urso can you have a look at the above comment to check?

**Comment by urso** [comment]
All in all in presence of filebeat I like to think of files as
channels/pipes/queues (I'm afraid I will use either name when commenting).
So for me the main question is: under which conditions are we fine with dropping
data in our channels?

> ignore_older
> 
> On Startup
> ...
>
> - File was not change in the ignore_older period: File is not read, file pointer is set to the end of the file
> - File was not change in the ignore_older period but we have it in the registrar (read before): File pointer will be set to the end
>

Not sure, what happens if file was read before and filebeat was stopped itself
for ignore_older period? Shouldn't we continue reading the file then? It's not
the producer it's fault filebeat didn't run.

> ignore_older
>
> Running
> ...
> - New file added which is NOT changed in ignore_older: File is not read, file pointer is set to the end
>

Not sure I like this behavior. if file was added we should have seen it in last scan. So file should
have been read, but is not due to scan frequency? Racey behavior... I'd rather opt for deterministic behavior and assume file was seen in time.

> - File was not change in the ignore_older period but we have it in the registrar (read before): File pointer will be set to the end

Really set it to end of file? What if file update period is much bigger to ignore_older? Will all lines be sent? Will some lines be dropped? Will all content in file be ignored (scan_frequency <-> ignore_older dependency)?

We wan't to add configuration validation saying scan_frequency must always be much less then ignore_older?

We shouldn't (silently) drop events, just because producer is rather slow. Thinking of files as 'pipes/channels', I'd drop lines if lines are written faster then can be consumed (e.g. back pressure from network) or pipe is already very very full on startup. But then dropping is better defined by file/queue size, not by age (or a mix)?

> Questions:
>
> - Should files which fall under ignore_older be added to the registrar? The potential problem here is that registrar can get really large.
> - What are we doing with files we have in the registrar with offset that are
>   updated and were falling under ignore_older before. Do we start at the last
>   offset or from the end?

If we add it to registrar, we have an offset where to start reading the file.
But would it make a difference in the way the file is processed?

By adding files to registrar immediately, we can continue reading from 'right' offset. Whereas not inserting in registrar requires us to process the complete file. This clearly speaks for adding the file to the registrar.

Any other potential problems with not adding the file to the registrar?

> - Should we offer the possibility to disable ignore_older, means setting it to infinit? 0 could be used for that.

+1


> close_older
> ...

I see how close_older can be nice to have for the registrar and I mostly agree
with all points on close_older, but:

> The goal of close_older is not to have too many open files to save resources.
So we try to 'schedule' some resources on some 'unrelated' variable in
potentially dynamic environment.

To me it sounds like we're more interested in kind of a scheduler, giving
priorities to files based on config and update rate. Like highest priority can
be 'always_follow' which never closes any file handles (must be set by user),
followed by lower priorites. The prospector checks for updates + file size since
last read and decides about priority. If a file was not update for (whatever
timespan - close_older?) it's closed and the file handle is 'returned' to the
scheduler for use with another harvester. Plus harvesters can potentially be
preempted by sending a signal (close file and return handle to scheduler) and
continued by sending another signal (re-open file and continue reading).

> scan_frequency
>

What if scan itself takes very long?

What's the required factor between ignore_older and close_older?

> tail_files
>

I think tail_files should ensure no old log entries are sent when filebeat is
started the first time. from then on it should tail all content of found files.

If (big) new files have been added one can either start tailing them once they
are seen first or never tail them. In first case prospector/harvester must be
aware of logrotation. In presence of log-rotation newly seen files must not be
tailed if they just continue the logging of a rotated file.


> remove_older_state

This option really required?

I agree the registrar should do some garbage collection in general (always
enabled), but I wonder if this can be mixed with results from scan or
scan_frequency in another go routine finding files in registrar to be removed
from last scan result. (Maybe have rate how often gc should be run).

**Comment by ruflin** [comment]
@tbragin For the renaming of `ignore_older` to `ignore_inactive`. I suggest to keep the name as also LS uses the same naming. Also it would then probably be `close_inactive`.

**Comment by guyboertje** [comment]
@ruflin @tbragin - it depends on what idea we are trying to implant into the user's mind, older suggests elapsed time only whereas inactive suggests more.

**Comment by ruflin** [comment]
close_older implemented in https://github.com/elastic/beats/pull/718
