### ISSUE TITLE
Improve tail_files option to happen only at startup

### ISSUE THREAD

**Issue by monicasarbu** [elastic/filebeat#185]
The original issue: https://github.com/elastic/filebeat/pull/175

If tail_files is enabled, new files are read starting with the end of file instead of the beginning. 
The nice thing about this option is that if Filebeat is started for the first time, only the new log lines are processed. 
The downside is that in case of a rotated log file, it's possible that couple of log lines are missed until Filebeat discovers that the file was rotated.

**Comment by ruflin** [comment]
Closing this issue as this this would require that on startup filebeat would have to persist a state for all files around (including the ones falling under ignore_older). Otherwise it can't now if a file which was falling under ignore_older, if it is a new file or a file that was just updated. 

This can be potentially be solved by starting filebeat the first time with `-once` with tail_files enabled to do a first run and then change the config. https://github.com/elastic/beats/pull/2456
