### ISSUE TITLE
tcp input

### ISSUE THREAD

**Issue by philipmeadows** [elastic/filebeat#213]
Are there any plans to support tcp input of logstash messages which would then be forwarded onto a remote logstash instance.

What I would like to do would be to use something like https://github.com/logstash/logstash-logback-encoder#tcp-appenders to have my applications sending logs directly to a port on localhost and then use logstash forwarder/filebeat to forward that on to my remote logstash with logstash forwarder/filebeat taking care of buffering, SSL comms and failover.

**Comment by tsg** [comment]
While you can do that today with LS, because it has a Lumberjack output plugin, it sounds to me like this is a valid use case for Beats, because a beat doing this would take less RAM/CPU.

We're going to see if we want to make this it's own Beat or not, but I'd say it's something we'll have at some point.

**Comment by philipmeadows** [comment]
Excellent, thanks. I look forward to it.

**Comment by ddes** [comment]
+1
I'm also very interrested by this kind of feature.

**Comment by runningman84** [comment]
that would be really cool...

**Comment by steverigby** [comment]
Adding a +1 to this feature.

**Comment by chrusty** [comment]
+1 here too!

**Comment by mgcrea** [comment]
:+1: Heavily needed to replace fluentd.

**Comment by ruflin** [comment]
I will close this in favor of https://github.com/elastic/beats/issues/536 Lets continue the discussion there.
