### ISSUE TITLE
Throttling or rate limiting per input file

### ISSUE THREAD

**Issue by dgassaway** [elastic/filebeat#227]
Wondering as to the technical feasability and usefulness of this feature: being able to configure a maximum rate at which to ingest from individual file configurations as a method of upstream rate limiting, and simply just more deterministic results when using the shipper in a very busy environment.

The 'workaround' for this type of functionality as I understand it is to use a throttle filter in an upstream logstash instance.  But by that time, the 'work' of tailing, reading, and shipping a message has already been done.  Being able to limit individual file read effort in the harvesters would enable a managed QoS on log ingestion at the source.

There is a similar issue that's floated around in the logstash file input plugin, but does not seem to have a lot of traction: https://github.com/logstash-plugins/logstash-input-file/issues/17 .

**Comment by ruflin** [comment]
I think there are different points here. Probably the first that would be required is a general overall rate limiting for libbeat sending data to the hosts. Not sure if this would be based on number of events sent per second or the size of the events sent. Then the same would have to be implemented on the prospector level. I prefer the prospector level as it allows to define params for multiple files but also a prospector could only contain one file, so we have the full flexibility.

A challenge with throttling is where we do it. We could do it on the network level or as you describe above, based on the lines that are read. From a technical point I think especially throttling the number of lines read is not too hard to implement.

A goal of filebeat is to be as close to real time as possible, means getting the log files off the server as fast as possible to have the logs available in case of failure of the machine or also to use it for alerting. The above would go a little bit agains this principle but I can see that pushing all the log data during peaks could affect the network.

What is your main concern? Network traffic? Load on the client side? Server side not keeping up?

**Comment by urso** [comment]
For now I think the beats should deal with throttling, not libbeat (some throttling support can be provided as library though). For packetbeat we don't want to throttle in libbeat, as packetbeat might drop events when throttling is enabled. topbeat has a fixed rate for data acquisition. For filebeat throttling can make sense.

When adding filters some sampling might be added to libbeat (for use with packetbeat). Then adding throttling to libbeat makes more sense.

**Comment by dgassaway** [comment]
Thanks for the quick responses.  To be more clear, I also think the 'read lines' stage is the right place for throttling, not at the network level.  As I see it, the point would be to prevent the lines from entering the local filebeat pipeline at all.  For example, a file configured with a max read of 100 lines/sec generates 200 lines/sec - filebeat would read 100 lines and then go and do something else, and will return to that file later.  (Whether is is feasible "per second," and whether the right configuration is maximum lines, bytes, or a combination of the two is more dubious.)

Whether this is part of libbeat/beats/filebeat, I'll have to read the code a bit more to make sure my terminoligy is correct.  I think all the comments thus far are on the same wavelength, though.

More detail on the use case I'm thinking about:

My main concern is a busy "mult-tenant" environment where the log output could exceed the shippers ability to read it all.  My actual use case is using filebeat (actually, Logstash at the moment) as a shipper on a machine with a number (dozens+) of applications with a wide range of log output.  The behavior and latency between applications can get unpredictable if some of those applications have very high throughput, to the point exceeding the shippers ability to read fast enough, and some have low throughput.  If you can limit the read on the high-volume loggers, it lets you manage the overall expected log throughput more predictably.

**Comment by ruflin** [comment]
It sounds like the implementation for this could be quite simple. It would need a defined batch size and a timeout. So every time it reaches the batch size, the harvester goes to sleep for the timeout. 

Currently we already have quite some complexity in the harvester because of special cases and are doing refactoring to make it simpler. As soon as we reach this point, I could see this as a valuable addition. 

My worry in the above case is that it could happen, that the logger never catches up ...

@dgassaway In case you have some time to take a closer look at the code, it is probably inside the Harvest function in [log.go](https://github.com/elastic/filebeat/blob/master/harvester/log.go) where the magic should happen. Feel free to open a pull request.

**Comment by urso** [comment]
Some very simple algorithm to keep the bandwidth and reduce jitter might be the leaky bucket algorithm implemented with a channel. A second go-routine will read from the channel at a predefined rate (based on configured bandwidth) and forward read events to the spooler. But since we don't want to drop any events, the average output rate of filebeat must be >= average arrival rate + time interval for average rate should exceed lifetime of file to be forwarded.

If system is overly busy 24/7 and event arrival rate exceeds bandwidth limit events must be dropped, meaning sampling or any other active queue management strategy will be required (best based on entropy?). If events are written to file faster then can be read, events will be lost on file deletes after logrotation (until delay has become very very big). On the other hand, if we read lines about the time lines are written, content will be read from cache (from main memory, not from disk), potentially improving processing performance.

If applications write logfiles themselves, their output is limited by disk IO. Having enough applications doing so on hard drives can kill overall IO throughput anyway. I'm not really worried about not being able to read events fast enough in this case. Collecting/writing logs e.g. via syslog the limit is still I/O throughput and logs [might be dropped](https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/concepts-losing-messages.html) by syslog service. 

If system has peak times and periods of rest (e.g. at nights), some dynamic bandwidth adjustment would be optimal. Reduce log forwarding bandwidth during peak time (buffer events in log files) and increase dynamic bandwidth to catch up with buffered event at periods of rest. That is, we basically have a (dynamic?) scheduling problem.

A more global view on network level to dictate bandwidth limitations would be much more helpful in a dynamic environment to optimise total resource usage in your network (e.g. speak software define networks). All connections from beats to logstash/elasticsearch/redis are via TCP. Using traffic shaping (QOS) on these connections bandwidth usage can already be controlled. The TCP connection will generate some back pressure if filebeat tries to send events faster then can be processed. This back pressure will finally affect the harvester limiting the overall speed files will be processed. E.g. see [tc command](http://linux.die.net/man/8/tc) on linux.

On linux using cgroups and [blkio controller](http://www.mjmwired.net/kernel/Documentation/cgroups/blkio-controller.txt) you might be able to throttle I/O throughput for processes. Maybe this can be used to adjust filebeat input bandwidth.

All in all, this makes me wonder about the value of having some statically configurable bandwidth limitation right in filebeat (especially without filtering/sampling strategy).

**Comment by oazabir** [comment]
Adding my vote to this. We are in dire need of file specific lines/sec limit. Sometimes we get flood of traffic which floods our logs and then filebeat honestly tries to use all available processing power to ship them to logstash and logstash dies, taking everything else with it. Not to mention filebeat itself consuming way too much CPU on the server when we badly need CPU to be free.

**Comment by ruflin** [comment]
Closing in favor of https://github.com/elastic/beats/issues/662 to have it in the beats repo.
