### ISSUE TITLE
Make requirement to update logstash-input-beats more obvious

### ISSUE THREAD

**Issue by ruflin** [elastic/filebeat#229]
Logstash 2.0.0 ships with the logstash-input-beats version 0.9.2 which is for example incompatible with @timestamp value. In the documentation we should make it much more obvious that currently the plugin has to be updated always, be it 1.5.4 or 2.0.

I also find it a little bit confusing, that when I download 2.0 and run install, I still have the old version because the plugin already existed. I'm aware that this is default behaviour and makes sense from a technical point of view. But it would be nice to have a notification here at least the the plugin is no the most recent version:
```
$ ./bin/plugin install logstash-input-beats
Validating logstash-input-beats
Installing logstash-input-beats
Installation successful
$ ./bin/plugin update logstash-input-beats
Updating logstash-input-beats
Updated logstash-input-beats 0.9.2 to 0.9.6
```

@ph Is there a command that installs the plugin in case it doesn't exist, but updates it if it is already there?

**Comment by shaggyz** [comment]
@ruflin thanks for this tip!!!

**Comment by ph** [comment]
@ruflin currently it need to be 2 commands, `bin/plugin install` wont start an update process if the plugin is already present. 

This might be something we need to fix to at least to provide better feedback.

**Comment by Mat1tee** [comment]
How can I install this update behind a firewall?

**Comment by Mat1tee** [comment]
After trying to install it, I'm getting an error about fetching specs from rubygems.org...

**Comment by ruflin** [comment]
@Mat1tee What is exactly the error you get?

**Comment by ph** [comment]
@Mat1tee logstash has some issue installing plugins when you are behind a firewall, its mainly because of other dependencies that the plugin has.

We have just merged this PRs https://github.com/elastic/logstash/pull/3404 that should give you some options to install plugins when you are behind a firewall.

**Comment by Orabig** [comment]
This is an issue, as the dockerized logstash (https://hub.docker.com/_/logstash/) contains this old-buggy version.
And it's not always easy/possible to have sufficient network access to upgrade some gem inside a dockerized application...
Btw, I'm copying here the error message I get, because it is very hard to find any information on this one, so people having the same issue will be happy (I guess) to get this information : 


Beats input: unhandled exception {:exception=>#<TypeError: The field '@timestamp' must be a (LogStash::Timestamp, not a String (2015-11-20T15:25:40.208Z)>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/event.rb:138:in `[]='", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/logstash/inputs/beats.rb:138:in `create_event'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/logstash/inputs/beats.rb:138:in `create_event'",
(....)
"Concurrent$$JavaExecutorService$$Job_1581663657.gen:13:in `run'"], :level=>:error}

**Comment by Orabig** [comment]
I've created an updated docker image to fix this : https://hub.docker.com/r/orabig/logstash-fixed/

It's based on the official logstash repository with the additional @ruflin upgrade command.

(Also an entrypoint bug has been fixed)

**Comment by ruflin** [comment]
@Orabig Thanks for providing the info above. Be aware that the "official" image is not from Elastic itself.

**Comment by dedemorton** [comment]
@ruflin We've added a section here about updating the plugin: https://www.elastic.co/guide/en/beats/libbeat/current/getting-started.html#logstash-input-update. I think it's fairly obvious now. Can I close this issue, or is there anything else we need to say?

**Comment by ruflin** [comment]
@dedemorton One issue I spotted is that we say if you have 2.0 or below. I think it is the case for all LS versions as the plugin is constantly updated with new version. Or do I misunderstand something here?

**Comment by dedemorton** [comment]
@ruflin No, I'm the one who is misunderstanding. I think we added this section because 2.0 did not ship with the latest version of the beats input plugin, but I see now that the info is relevant for other users. Somehow I missed the idea that the plugin release cycle was separate from the Logstash release cycle. :-)

I don't see a command for checking whether the latest version of the plugin is installed. So I'll just say something like this:  

**Updating the Logstash Input Beats Plugin**
Plugins have their own release cycle and are often released independent of Logstash’s core release cycle. To ensure that you have the latest version of the Logstash Input Beats plugin, run the following command from your Logstash installation:
[...]

Does that sound OK?

**Comment by ruflin** [comment]
@dedemorton LGTM. I think important to note is that also older version of LS can get a plugin update. So even if you don't upgrade from 2.0 to 2.1 you can still get the updated plugin.
