### ISSUE TITLE
possibility to export a field containing the processed logfile owner

### ISSUE THREAD

**Issue by lhoss** [elastic/filebeat#315]
other log file properties could be exported as well
but the file's OS owner/user is probably the most useful.
Currently only the filename is exported (in the field 'source')

Example Use-Case:
* Apache Mesos Framework logs (written to /tmp/mesos by default), don't have the framework (for ex: 'spark job') user within the logs, but the user can be extracted from the file owner.
That's why it would be very helpful if  filebeat could export (to elastic search -> kibana) the owner of a log file (of course this could be optional, enabled by a new setting)

**Comment by lhoss** [comment]
anybody see the value of this *Enhancement* request  or it's not clear? (I updated the example use-case, hopefully more clear now) 
@ruflin maybe ?

**Comment by ruflin** [comment]
I definitively see the value of knowing who the user is. I'm not 100% sure it fits the filebeat model. The reason is that the owner stays mostly the same over the lifetime of the file and would be lots of duplicated data for each line (yes I know, we have parts of this already).

Is it just about knowing the user of the log file or is this a general problem? If yes, a separate beat could be used that does track file users, size etc. I wrote a small prototype for this here: https://github.com/ruflin/modbeat Be aware, that this is a personal prototype ;-)

**Comment by zorel** [comment]
I have the same problem. I send all the log files in graylog/elasticsearch, and there is no mean at the end to distinguish to whom belongs the line of log. As there is no information inside the logfile for that. The logs are sent with a path globbing to listen to new files, so I can't set fields for each stderr/stdout.

Sending the owner of the file make possible the "routing" at the end, and thus displaying it to the destination user.

Today, mesos does not support modifying the stderr/stdout path, or the format. Adding the userid/groupid https://golang.org/pkg/syscall/ (which kind of sucks because it does not seems portable) would help.

**Comment by ruflin** [comment]
I'm closing this issue in favor of https://github.com/elastic/beats/issues/1775 to make sure we keep it on the radar. All development happens in the beats repo now.
