### ISSUE TITLE
output > logstash > no connection

### ISSUE THREAD

**Issue by lookingcloudy** [elastic/filebeat#324]
First tried to proxy logstash from nginx, both over http and stream with basic authentication.  No go.  Turns out logstash/beats input does not support authentication (huh?). 

Next tried tried basic proxy with no TLS, no authentication.  Tried both http and stream.   No go.  Filebeats does not indicate a connection problem, says it is cycling through the logs, not connecting to nginx/beats.

Next tried connecting directly to logstash - no TLS, no proxy.  Same as above.  No error in the logs, no output.

Next tried sending directly to elasticsearch.  That resulted in an error due to no ping.

**Comment by andrewkroh** [comment]
As described in the documentation, the [Logstash output](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-configuration-details.html#logstash-output) uses the Lumberjack protocol. Since it does not use HTTP, neither a HTTP proxy nor HTTP Basic Authentication are going to work.

Filebeat (and all Beats) support TLS client authentication for both the Logstash and Elasticsearch outputs (as was answered in your discuss.elastic.co [posting](https://discuss.elastic.co/t/how-to-setup-filebeat-with-basic-auth-for-logstash-output/36937/8)). There is an open [issue](https://github.com/logstash-plugins/logstash-input-beats/issues/8) with the input plugin not verifying the client's certificate during the handshake.

Please follow [Logstash setup guide](https://www.elastic.co/guide/en/beats/libbeat/1.0.1/getting-started.html#logstash-setup) to get a simple Logstash server running with the logstash-input-beats plugin. Then go from there.

If you want to turn on more verbose logging to the console, then you can run Filebeat in the foreground like so `./filebeat -c /etc/filebeat/filebeat.yml -e -v -d "*"`. You can also configure [logging](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-configuration-details.html#_logging_options) through the config file. The options are all in the documentation.

Please use https://discuss.elastic.co for general questions and troubleshooting. We would like to reserve Github issues for specific bug reports or features being are tracking.

**Comment by ruflin** [comment]
Closing. See also https://github.com/elastic/filebeat/issues/323
