### ISSUE TITLE
How to send json directly to elasticsearch ?

### ISSUE THREAD

**Issue by YLombardi** [elastic/filebeat#348]
Hi.

I have a spring application that use logback and LogstashEncoder to directly parse logs and generate json files.
I want to use filebeat to read the json file and send it to Elasticsearch without adding anything.

Currently, a line in my json file is like this : 

```
{"@timestamp":"2016-04-13T10:19:51.971+02:00","@version":1,"message":"A log message","logger_name":"a.java.class","thread_name":"default task-28","level":"DEBUG","level_value":10000,"HOSTNAME":"myhost","user":"aUser","RequestID":"4f8784f8-f5d4-4d31-9e0c-e805b328d661","app-name":"MyAppName"}
```

As you can see, it is already parsed. I want to send this to Elasticsearch but filebeat seems to wrap the line and add informations.

I obtain this : 

```
@timestamp:
    13/04 10:19:52
beat.hostname:
    myHost
beat.name:
    myHost
count:
    1
fields:
    - 
input_type:
    log
message:
    {"@timestamp":"2016-04-13T10:19:51.971+02:00","@version":1,"message":"A log message","level":"DEBUG","level_value":10000,"HOSTNAME":"myhost","user":"aUser","RequestID":"4f8784f8-f5d4-4d31-9e0c-e805b328d661","app-name":"MyAppName"}
offset:
    20,423,371
source:
    /var/log/wildfly/myApp/file.json
type:
    atype
_id:
    AVQO54Xl8y3gF0aTmSWk
_type:
    atype
_index:
    filebeat-2016.04.13
_score:
```

What can I do to remove this "wrapper" and send raw data with filebeat ?

Here is my filebeat.yml : 

```
filebeat:
prospectors:
-
paths:
- /var/log/wildfly/myApp/*.json
input_type: log
document_type: aType
registry_file: /var/lib/filebeat/registry
output:
elasticsearch:
hosts: ["myelastic:9200"]
index: "filebeat"
```

**Comment by tsg** [comment]
Note that this repository is no longer used, Filebeat moved to https://github.com/elastic/beats. Also, for questions like this, we prefer to have topics opened on https://discuss.elastic.co/c/beats/ rather than issues in Github.

The next major version of Filebeat (for which you can try the alpha1 release if you'd like) has native JSON support, so you can send the contents of the original dictionary. See the docs [here](https://www.elastic.co/guide/en/beats/filebeat/master/configuration-filebeat-options.html#config-json).

**Comment by YLombardi** [comment]
Thanks for your answer. I will look at the discuss site.
